/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const ToolboxLazyRouteImport = createFileRoute('/toolbox')()
const ProjectsLazyRouteImport = createFileRoute('/projects')()
const PlaygroundLazyRouteImport = createFileRoute('/playground')()
const IndexLazyRouteImport = createFileRoute('/')()
const ToolboxIndexLazyRouteImport = createFileRoute('/toolbox/')()
const ToolboxFfmpegLazyRouteImport = createFileRoute('/toolbox/ffmpeg')()

const ToolboxLazyRoute = ToolboxLazyRouteImport.update({
  id: '/toolbox',
  path: '/toolbox',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/toolbox.lazy').then((d) => d.Route))
const ProjectsLazyRoute = ProjectsLazyRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))
const PlaygroundLazyRoute = PlaygroundLazyRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/playground.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ToolboxIndexLazyRoute = ToolboxIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolboxLazyRoute,
} as any).lazy(() => import('./routes/toolbox/index.lazy').then((d) => d.Route))
const ToolboxFfmpegLazyRoute = ToolboxFfmpegLazyRouteImport.update({
  id: '/ffmpeg',
  path: '/ffmpeg',
  getParentRoute: () => ToolboxLazyRoute,
} as any).lazy(() =>
  import('./routes/toolbox/ffmpeg.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/playground': typeof PlaygroundLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/toolbox': typeof ToolboxLazyRouteWithChildren
  '/toolbox/ffmpeg': typeof ToolboxFfmpegLazyRoute
  '/toolbox/': typeof ToolboxIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/playground': typeof PlaygroundLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/toolbox/ffmpeg': typeof ToolboxFfmpegLazyRoute
  '/toolbox': typeof ToolboxIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/playground': typeof PlaygroundLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/toolbox': typeof ToolboxLazyRouteWithChildren
  '/toolbox/ffmpeg': typeof ToolboxFfmpegLazyRoute
  '/toolbox/': typeof ToolboxIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/projects'
    | '/toolbox'
    | '/toolbox/ffmpeg'
    | '/toolbox/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/playground' | '/projects' | '/toolbox/ffmpeg' | '/toolbox'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/projects'
    | '/toolbox'
    | '/toolbox/ffmpeg'
    | '/toolbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PlaygroundLazyRoute: typeof PlaygroundLazyRoute
  ProjectsLazyRoute: typeof ProjectsLazyRoute
  ToolboxLazyRoute: typeof ToolboxLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toolbox': {
      id: '/toolbox'
      path: '/toolbox'
      fullPath: '/toolbox'
      preLoaderRoute: typeof ToolboxLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolbox/': {
      id: '/toolbox/'
      path: '/'
      fullPath: '/toolbox/'
      preLoaderRoute: typeof ToolboxIndexLazyRouteImport
      parentRoute: typeof ToolboxLazyRoute
    }
    '/toolbox/ffmpeg': {
      id: '/toolbox/ffmpeg'
      path: '/ffmpeg'
      fullPath: '/toolbox/ffmpeg'
      preLoaderRoute: typeof ToolboxFfmpegLazyRouteImport
      parentRoute: typeof ToolboxLazyRoute
    }
  }
}

interface ToolboxLazyRouteChildren {
  ToolboxFfmpegLazyRoute: typeof ToolboxFfmpegLazyRoute
  ToolboxIndexLazyRoute: typeof ToolboxIndexLazyRoute
}

const ToolboxLazyRouteChildren: ToolboxLazyRouteChildren = {
  ToolboxFfmpegLazyRoute: ToolboxFfmpegLazyRoute,
  ToolboxIndexLazyRoute: ToolboxIndexLazyRoute,
}

const ToolboxLazyRouteWithChildren = ToolboxLazyRoute._addFileChildren(
  ToolboxLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PlaygroundLazyRoute: PlaygroundLazyRoute,
  ProjectsLazyRoute: ProjectsLazyRoute,
  ToolboxLazyRoute: ToolboxLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
